export const cellularMockData = {
    Cellular: {
        RoamingEnabled: 0,
        RoamingStatus: 'Home',
        ConnectionStatus: 'Up',
        ConnectionTime: 30,
        InterfaceEnable: 1,
        PreferredAccessTechnology: 'Auto',
        SupportedAccessTechnologies: 'LTE,NR',
        IMEI: '864624060070580',
        IMSI: '466011202835208',
        ICCID: '89886012137828428906',
        USIMStatus: 'Valid',
        PLMN: '46601',
        OperatorName: 'Far EasTone',
        PIN: '',
        PINCheck: 'Off',
        PINRemain: 'None',
        PUKRemain: 'None',
        APN: '',
        Username: '',
        Password: '',
        X_PRPLWARE_COM_IPType: 'ipv4v6',
        RSSI: -111,
        RSRP: -140,
        RSRQ: -20,
        SINR: 'None',
        PCI: 'None',
        CellID: 'None',
        ConnectedBand: 'None',
        DLEarfcn: 'None',
        UplinkCurrentSpeed: 'None',
        DownlinkCurrentSpeed: 'None',
        VoiceUplinkTraffic: 'None',
        VoiceDownlinkTraffic: 'None',
        PacketsReceived: 52,
        PacketsSent: 77,
        BytesReceived: 5111,
        BytesSent: 6278
    }
};
